config/routes.rb
Rails.application.routes.draw do

  root 'gardens#index'

  resources :gardens
  resources :authors
  resources :works

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :works
  has_many :garden_authors
  has_many :gardens, through: :garden_authors

end

app/models/garden.rb
class Garden < ActiveRecord::Base

  has_many :garden_authors
  has_many :authors, through: :garden_authors

  def author_names
    authors.map { |x| x.name }.join(", ")
  end

end

app/models/garden_author.rb
class GardenAuthor < ActiveRecord::Base

  belongs_to :author
  belongs_to :garden

end

app/models/work.rb
class Work < ActiveRecord::Base

  belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save!
      redirect_to @author
    else
      render 'new'
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
  end

  private

    def author_params
      params.require(:author).permit(:name)
    end

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

  def index
    @gardens = Garden.all
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)

    if @garden.save!
      redirect_to @garden
    else
      render 'new'
    end
  end

  def show
    @garden = Garden.find(params[:id])
    @walk = Gardening::Walker.new(@garden).walk
  end

  def edit
    @garden = Garden.find(params[:id])
  end

  def update
    @garden = Garden.find(params[:id])

    if @garden.update(garden_params)
      redirect_to @garden
    else
      render 'edit'
    end
  end

  def destroy
    @garden = Garden.find(params[:id])
  end

  private

    def garden_params
      params.require(:garden).permit(:name, author_ids: [])
    end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def index
    @works = Work.all
  end

  def new
    @work = Work.new(author_id: params[:author])
  end

  def create
    @work = Work.new(work_params)

    if @work.save!
      redirect_to @work
    else
      render 'new'
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])

    if @work.update(work_params)
      redirect_to @work
    else
      render 'edit'
    end
  end

  def destroy
    @work = Work.find(params[:id])
  end

  private

    def work_params
      params.require(:work).permit(:name, :text, :author_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= semantic_form_for @author do |f| %>
        <%= f.inputs do %>
          <%= f.input :name %>
        <% end %>
        <%= f.actions do %>
          <%= f.action :submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<div id="main-container" class="container">
  <%= link_to "add a new author", new_author_path %>
  <div class="row">
    <div class="col-xs-5">
      <table>
        <tr>
          <th>author</th>
          <th></th>
        </tr>

        <% @authors.each do |author| %>
          <tr>
            <td><%= link_to author.name, author_path(author) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<%= render partial: "form" %>

app/views/authors/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= @author.name %>
      <%= link_to "edit name", edit_author_path(@author) %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5">
      <table>
        <tr>
          <th width="30%">work</th>
          <th width="30%"></th>
          <th width="30%"></th>
        </tr>
      <%= link_to "add new work for #{@author.name}", new_work_path(author: @author) %>
        <% @author.works.each do |work| %>
          <tr>
            <td><%= link_to work.name, work_path(work) %></td>
            <td><%= link_to "edit", edit_work_path(work) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/gardens/_form.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= semantic_form_for @garden do |f| %>
        <%= f.inputs do %>
          <%= f.input :name %>
          <%= f.input :authors, :as => :select %>
        <% end %>
        <%= f.actions do %>
          <%= f.action :submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/index.html.erb
<div id="main-container" class="container">
  <%= link_to "create a new garden", new_garden_path %>
  <div class="row">
    <div class="col-xs-5">
      <table>
        <tr>
          <th width="30%">garden</th>
          <th width="30%">authors</th>
        </tr>

        <% @gardens.each do |garden| %>
          <tr>
            <td><%= link_to garden.name, garden_path(garden) %></td>
            <td><%= garden.author_names %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<%= render partial: "form" %>

app/views/gardens/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <strong>Name:</strong>
      <%= @garden.name %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-5">
      <strong>Authors:</strong>
      <%= @garden.author_names %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-5">
        <%= @walk %>
    </div>
  </div>

  <%= link_to "modify this garden", edit_garden_path(@garden) %>
  <%= link_to "take another walk", garden_path(@garden) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>glass.gardens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
     <h1>glass.gardens</h1>
     <%= link_to "gardens", gardens_path %>
     <%= link_to "authors", authors_path %>
     <hr>
  </div>

  <%= yield %>
</body>
</html>

app/views/works/_form.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= semantic_form_for @work do |f| %>
        <%= f.inputs do %>
          <%= f.input :name %>
          <%= f.input :author_id, :as => :hidden %>
          Author: <%= @work.author.name %>
          <%= f.input :text %>
        <% end %>
        <%= f.actions do %>
          <%= f.action :submit, :label => "save" %>
        <% end %>
      <% end %>

      <%= link_to "back to #{@work.author.name}", author_path(@work.author) %>
    </div>
  </div>
</div>

app/views/works/edit.html.erb
<%= render partial: "form" %>

app/views/works/new.html.erb
<%= render partial: "form" %>

app/views/works/show.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-5">
      <%= @work.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-5">
      <%= @work.text %>
      <%= link_to "back to #{@work.author.name}", author_path(@work.author) %>
    </div>
  </div>
</div>